import "dart:math";

class Inspiration {
  static const Map<String, List<String>> frases = {
    "Buddha": [
      "Alégrate porque todo lugar es aquí y todo momento es ahora",
      "No es más rico quien más tiene, sino quien menos necesita",
      "El dolor es inevitable, pero el sufrimiento es opcional",
      "Cuida el exterior tanto como el interior, porque todo es uno",
      "El odio no disminuye con el odio. El odio disminuye con el amor",
      "Para entender todo, es necesario olvidarlo todo",
      "La paz viene de adentro, no la busques afuera",
      "En lo que pensamos, justamente en eso nos convertiremos",
      "Tu propósito en la vida es encontrar un propósito, y entregar a él todo tu corazón",
      "El insensato que reconoce su insensatez es un sabio. Pero un insensato que se cree sabio es, en verdad, un insensato",
      "Nuestras buenas y malas acciones nos siguen casi como una sombra",
      "Nadie te castigará por tu enfado; será él mismo el encargado de castigarte",
      "Hay tres cosas que no pueden ocultarse por mucho tiempo: el sol, la luna y la verdad",
      "La muerte no se teme, si la vida se ha vivido sabiamente",
      "No vivas del pasado, no imagines el futuro, concéntrate en el momento presente",
      "Si puedes apreciar el milagro que encierra una sola flor, tu vida cambiará por completo",
      "Tú te mereces tu cariño y afecto",
      "Una mente disciplinada trae felicidad",
      "El amor verdadero nace de la comprensión",
      "Conquistarse a uno mismo es una tarea más grande que conquistar a otros",
      "Solo podemos perder aquello a lo que nos aferramos",
      "Es mejor viajar bien que llegar",
      "A un loco se le conoce por sus actos, a un sabio también",
      "Aferrarse a la rabia es como agarrarse a un carbón caliente con la intención de tirárselo a alguien; tú eres el que te quemas",
      "En cualquier batalla pierden vencedores y vencidos",
      "Ni tu peor enemigo puede hacerte tanto daño como tus propios pensamientos",
      "Para enseñar a los demás, primero has de hacer tú algo muy duro: has de enderezarte a ti mismo",
      "No hay incendio como la pasión: no hay ningún mal como el odio",
      "La riqueza consiste mucho más en el disfrute que en la posesión",
      "Si añades un poco a lo poco, y lo haces con frecuencia, pronto poco llegará a ser mucho",
      "Tu deber es descubrir tu mundo y después entregarte a él con todo tu corazón",
      "Si tiene solución, ¿por qué lloras? Si no tiene solución, ¿por qué lloras?",
      "Lo que hoy somos descansa en lo que ayer pensamos, y nuestros actuales pensamientos forjan nuestra vida futura",
      "Con nuestros pensamientos creamos el mundo",
      "Se pueden encender miles de velas con una sola vela, y la vida de la vela no se acortará.",
      "Duda de todo. Encuentra tu propia luz",
      "La máxima victoria es la que se gana sobre uno mismo",
      "No sobrestimes lo que has recibido ni envidies a otros; el que envidia no tiene paz",
      "Cada mañana nacemos de nuevo. Lo que hacemos hoy es lo que más importa",
      "Si no cambiamos de dirección, podemos terminar donde empezamos",
      "Al igual que una serpiente cambia de piel, debemos abandonar nuestro pasado una y otra vez",
      "La bondad debe convertirse en nuestra forma natural de vida, no en la excepción",
      "Nada es para siempre, excepto el cambio",
      "No hay un camino a la felicidad: la felicidad es el camino",
      "No creas nada, no importa donde lo leas o quien lo dijo, no importa si lo he dicho yo, a no ser que esté de acuerdo con tu propia razón y sentido común",
      "Un momento puede cambiar un día, un día puede cambiar una vida y una vida puede cambiar el mundo",
      "Si tu compasión no te incluye a ti mismo, es incompleta",
      "Sólo hay dos errores que se comenten en el camino a la verdad: No empezar y no llegar hasta el final",
      "Lo que eres es lo que has sido. Lo que serás es lo que haces a partir de ahora",
      "La amistad es la única cura para el odio, la única garantía de la paz",
      "La felicidad es un artículo maravilloso: cuanto más se da, más le queda a uno",
      "Una jarra se llena gota a gota",
      "Es capaz el que piensa que es capaz",
      "Pon tu corazón a hacer el bien. Si lo haces una y otra vez, se te llena de alegría",
      "Si no somos capaces de cuidar de los demás cuando necesitan ayuda, ¿quién cuidará de nosotros?",
      "El camino no está en el cielo; el camino se encuentra en el corazón",
      "Nunca he conocido a nadie tan ignorante del que no pudiera aprender algo",
      "Toma consciencia de dónde te encuentras; de lo contrario perderás tu vida",
      "Miles de velas pueden ser encendidas a partir de una sola, y la vida de esa vela no se acortará"
          "La felicidad nunca disminuirá por ser compartida",
      "El pasado ya se ha ido, el futuro todavía no está aquí. Sólo hay un momento en el que vives, y es el momento presente",
    ],
    "Dalai Lama XIV": [
      "If a problem is fixable, if a situation is such that you can do something about it, then there is no need to worry. If it's not fixable, then there is no help in worrying. There is no benefit in worrying whatsoever",
      "Happiness is not something ready made. It comes from your own actions",
      "If you think you are too small to make a difference, try sleeping with a mosquito",
      "Know the rules well, so you can break them effectively",
      "Remember that the best relationship is one in which your love for each other exceeds your need for each other",
      "Silence is sometimes the best answer",
      "Our prime purpose in this life is to help others. And if you can't help them, at least don't hurt them",
      "Choose to be optimistic, it feels better",
      "Remember that sometimes not getting what you want is a wonderful stroke of luck",
      "Judge your success by what you had to give up in order to get it",
      "We can never obtain peace in the outer world until we make peace with ourselves",
      "Take into account that great love and great achievements involve great risk",
      "Every day, think as you wake up: Today I am fortunate to be alive, I have a precious human life, I am not going to waste it",
      "The goal is not to be better than the other man, but your previous self",
      "Consider carefully: what prevents you from living the way you want to live your life?",
      "An open heart is an open mind",
      "It is very rare or almost impossible that an event can be negative from all points of view",
      "Share your knowledge. It is a way to achieve immortality",
      "Give the ones you love wings to fly, roots to come back, and reasons to stay",
      "If you want others to be happy, practice compassion. If you want to be happy, practice compassion",
      "Just one small positive thought in the morning can change your whole day"
    ],
    "Mahatma Gandhi": [
      "Live as if you were to die tomorrow. Learn as if you were to live forever",
      "A man is but a product of his thoughts. What he thinks he becomes",
      "Happiness is when what you think, what you say, and what you do are in harmony",
      "The weak can never forgive. Forgiveness is an attribute of the strong",
      "An ounce of practice is worth a thousand words",
      "Freedom is not worth having if it does not include the freedom to make mistakes",
      "The best way to find yourself is to lose yourself in the service of others",
      "Glory lies in the attempt to reach one’s goal and not in reaching it",
      "The future depends on what you do today",
      "Earth provides enough to satisfy every man’s needs, but not every man’s greed",
      "Strength does not come from physical capacity. It comes from an indomitable will",
      "You don’t know who is important to you until you actually lose them",
      "You may never know what results come of your actions, but if you do nothing, there will be no results",
      "I cannot conceive of a greater loss than the loss of one’s self-respect",
      "A ‘No’ uttered from the deepest conviction is better than a ‘Yes’ merely uttered to please, or worse, to avoid trouble",
    ],
    "Master Yoda": [
      "Try not! Do or do not. There is no try...",
      "Fear is the path to the dark side. Fear leads to anger. Anger leads to hate. Hate leads to suffering",
      "Luke: I don't believe it! Yoda: That.... is why you fail",
      "The greatest teacher, failure is",
      "Always pass on what you have learned",
      "Many of the truths that we cling to depend on our point of view",
    ],
    "Gandalf": [
      "All We Have To Do Is Decide What To Do With The Time That Is Given To Us",
      "Many that live deserve death. And some that die deserve life. Can you give it to them? Then do not be too eager to deal out death in judgement",
      "He that breaks a thing to find out what it is has left the path of wisdom",
      "It is not despair, for despair is only for those who see the end beyond all doubt. We do not.",
      "For even the very wise cannot see all ends",
      "You Must Trust Yourself. Trust Your Own Strength",
      "Death Is Just Another Path - One That We All Must Take",
      "The World Is Not In Your Books And Maps. It Is Out There",
    ],
    "Tyler Durden": [
      "It’s only after we’ve lost everything that we’re free to do anything",
      "You are not your job, you’re not how much money you have in the bank. You are not the car you drive. You’re not the contents of your wallet. You're not your fucking khakis",
      "If you don’t claim your humanity you will become a statistic",
      "I don’t want to die without any scars",
      "Nothing is static, everything is evolving, everything is falling apart",
      "You are not special. You’re not a beautiful and unique snowflake. You’re the same decaying organic matter as everything else. We’re all part of the same compost heap",
      "This is your life and its ending one minute at a time",
      "Without pain, without sacrifice we would have nothing. Like the first monkey shot into space",
    ],
    "William Wallace": [
      "Every man dies, but not every man trully lives",
      "We all end up dead, it's just a question of how and why",
      "There are wars, there is pain, there is suffering, and there is even death. But none of these things prepare you for Monday morning",
    ],
    "Don Vito Corleone": [
      "Great men are not born great, they grow great",
      "Never let anyone know what you are thinking",
      "Cause a man who doesn’t spend time with his family can never be a real man",
      "Never hate your enemies, it affects your judgement",
      "Forgive. Forget. Life is full of misfortunes",
    ],
    "Martin Luther King Jr.": [
      "We are not makers of history. We are made by history",
      "Every man must decide whether he will walk in the light of creative altruism or in the darkness of destructive selfishness",
      "We must use time creatively, in the knowledge that the time is always ripe to do right",
      "All labor that uplifts humanity has dignity and importance and should be undertaken with painstaking excellence",
      "An individual has not started living until he can rise above the narrow confines of his individualistic concerns to the broader concerns of all humanity",
      "Shallow understanding from people of good will is more frustrating than absolute misunderstanding from people of ill will",
      "The quality, not the longevity of one's life is what's important",
      "Love is the only force capable of transforming an enemy into friend",
      "He who is devoid of the power to forgive is devoid of the power to love",
      "I have decided to stick with love. Hate is too great a burden to bear",
      "If you can’t fly then run, if you can’t run then walk, if you can’t walk then crawl, but whatever you do you have to keep moving forward",
      "Only in the darkness can you see the stars",
      "Let no man pull you so low as to hate him",
      "There comes a time when one must take a position that is neither safe nor politic nor popular, but he must take it because his conscience tells him it is right",
      "No one really knows why they are alive until they know what they’d die for",
      "A man who won’t die for something is not fit to live",
      "We must accept finite disappointment, but never lose infinite hope",
      "Those who are not looking for happiness are the most likely to find it, because those who are searching forget that the surest way to be happy is to seek happiness for others",
      "Whatever your life’s work is, do it well. A man should do his job so well that the living, the dead, and the unborn could do it no better",
      "Everything that we see is a shadow cast by that which we do not see",
      "A genuine leader is not a searcher for consensus but a molder of consensus",
      "Our lives begin to end the day we become silent about things that matter",
      "The ultimate measure of a man is not where he stands in moments of comfort and convenience, but where he stands at times of challenge and controversy",
      "If I cannot do great things, I can do small things in a great way",
      "I came to the conclusion that there is an existential moment in your life when you must decide to speak for yourself; nobody else can speak for you",
      "Our scientific power has outrun our spiritual power. We have guided missiles and misguided men",
      "Nonviolence means avoiding not only external physical violence but also internal violence of spirit. You not only refuse to shoot a man, but you refuse to hate him",
    ]
  };

  static Map<String, String> getInspired() {
    final totalFrases =
        frases.values.reduce((total, entry) => [...total, ...entry]);

    final indexFrase = Random().nextInt(totalFrases.length);
    final frase = totalFrases[indexFrase];

    String author = '';
    int authorIndex = 0;
    int accum = 0;
    while (accum <= indexFrase) {
      author = frases.keys.elementAt(authorIndex);
      accum += frases[author]!.length;
      authorIndex++;
    }

    return {author: frase};
  }
}
